title: Xiangyi Li's Homepage
page-top-title: Xiangyi Li
top-section-bg-text: Statistics and Data Science
home-subtitle: Xiangyi Li&ensp;|&ensp; 李祥毅
copyright-text: '&copy; Xiangyi Li 2023-2024. All Rights Reserved.'
